name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Generate config.js
      run: sed -i "s/GOOGLE_ANALYTICS_ID/$GOOGLE_ANALYTICS_ID/g" .vuepress/config.js
      env:
        GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

    - name: Install jq
      run: sudo apt-get install jq -y

    - name: Create VERSION page
      run: "echo '```'$(jq -r .version package.json)'```' > version.md"

    - name: Check config.js (2)
      run: "cat .vuepress/config.js | grep ga"
 
    - name: Vuepress deploy
      uses: jenkey2011/vuepress-deploy@1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build
        TARGET_BRANCH: gh-pages
        BUILD_DIR: .vuepress/dist
